version: "3"
services:
  ethereum:
    image: rwthacis/monitored-geth-client
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545/tcp
      - 8546:8546/tcp
    environment:
      GETH_VERBOSITY: "3"
      ETHEREUM_DATA_DIR: /root/.ethereum/devchain
    volumes:
      - ethereumStoragePersistent:/root/.ethereum/devchain
    command: /root/start.sh
  backend:
    image: rwthacis/hye-youtube-proxy
    environment:
      LAS2PEER_ETH_HOST: ethereum:8545
      HYE_SERVICE_AGENT_NAME: hyeAgent
      HYE_SERVICE_AGENT_PW: changeme
#    volumes:
#      - proxyNodeStorage:/app/HyE-YouTube-Proxy/node-storage
    ports:
      - 9011:9011/udp
      - 9011:9011/tcp
    depends_on:
      - ethereum
  l2pservices:
    build: l2pservices/.
    environment:
      LAS2PEER_PORT: 9012
      LAS2PEER_ETH_HOST: ethereum:8545
      BOOTSTRAP: "backend:9011"
      CONTACT_STORER_NAME: hyeAgent
      CONTACT_STORER_PW: changeme
    volumes:
      - ./i5.las2peer.registry.data.RegistryConfiguration.properties:/src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties
#      - servicesNodeStorage:/src/node-storage
    depends_on:
      - backend
  mysql:
    image: mysql:5.7
    volumes:
      - mysqlStorage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
  mllib:
    image: rwthacis/python-mllib
    volumes:
      - ./GoogleNews-vectors-negative300.bin:/etc/GoogleNews-vectors-negative300.bin
    environment:
      MODEL_LOCATION: /etc/GoogleNews-vectors-negative300.bin
  recommendations:
    image: rwthacis/hye-youtube-recommendations
    environment:
      LAS2PEER_PORT: 9013
      LAS2PEER_ETH_HOST: ethereum:8545
      BOOTSTRAP: "backend:9011"
      MY_SQL_HOST: mysql
      ML_LIB_URL: "http://mllib:8000/"
      MY_SQL_USER_NAME: hye
      MY_SQL_USER_PW: changeme
      HYE_SERVICE_AGENT_NAME: hyeAgent
      HYE_SERVICE_AGENT_PW: changeme
    volumes:
      - ./i5.las2peer.registry.data.RegistryConfiguration.properties:/src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties
#      - recommendationsNodeStorage:/src/node-storage
    depends_on:
      - backend
      - mysql
      - mllib
  frontend:
    image: rwthacis/hye-youtube-frontend
    depends_on:
      - l2pservices
  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:8081
    depends_on:
      - frontend
volumes:
  ethereumStoragePersistent: {}
  servicesNodeStorage: {}
  proxyNodeStorage: {}
  recommendationsNodeStorage: {}
  mysqlStorage: {}
