apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ethereum
  name: ethereum
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ethereum
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ethereum
    spec:
      containers:
        - args:
            - /root/start.sh
          env:
            - name: ETHEREUM_DATA_DIR
              value: /root/.ethereum/devchain
            - name: GETH_VERBOSITY
              value: "3"
          image: rwthacis/monitored-geth-client
          name: ethereum
          ports:
            - containerPort: 30303
              protocol: UDP
            - containerPort: 30303
            - containerPort: 8545
            - containerPort: 8546
          resources: {}
          volumeMounts:
            - mountPath: /root/.ethereum/devchain
              name: ethereum-storage-persistent
      restartPolicy: Always
      volumes:
        - name: ethereum-storage-persistent
          persistentVolumeClaim:
            claimName: ethereum-storage-persistent
status: {}
