apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ethereum
  name: ethereum
spec:
  ports:
    - name: "30303"
      port: 30303
      protocol: UDP
      targetPort: 30303
    - name: 30303-tcp
      port: 30303
      targetPort: 30303
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: "8546"
      port: 8546
      targetPort: 8546
  selector:
    io.kompose.service: ethereum
status:
  loadBalancer: {}
