apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: l2pservices
  name: l2pservices
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: l2pservices
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: l2pservices
    spec:
      containers:
        - env:
            - name: BOOTSTRAP
              value: 137.226.232.70:32077
            - name: LAS2PEER_PORT
              value: '32079'
            - name: NODE_ID_SEED
              value: '3'
            - name: CONTACT_STORER_NAME
              value: hyeAgent
            - name: CONTACT_STORER_PW
              value: changeme
          ports:
          - containerPort: 32079
            protocol: TCP
          - containerPort: 32079
            protocol: UDP
          image: krapotke/l2pservices
          name: l2pservices
          resources: {}
          volumeMounts:
            - mountPath: /src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties
              name: registry-config-volume
              subPath: i5.las2peer.registry.data.RegistryConfiguration.properties
            - mountPath: /app/las2peer/node-storage
              name: node-storage
      restartPolicy: Always
      volumes:
        - name: node-storage
          persistentVolumeClaim:
            claimName: l2pservices-node-storage
        - name: registry-config-volume
          configMap:
            name: registry-config
status: {}
