apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: l2pservices
  name: l2pservices
spec:
  ports:
    - name: "32079tcp"
      port: 32079
      targetPort: 32079
      protocol: TCP
      nodePort: 32079
    - name: "32079udp"
      port: 32079
      targetPort: 32079
      protocol: UDP
      nodePort: 32079
  selector:
    io.kompose.service: l2pservices
  type: NodePort
status:
  loadBalancer: {}
