apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mllib
  name: mllib
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mllib
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mllib
    spec:
      containers:
        - env:
            - name: MODEL_LOCATION
              value: /app/model/GoogleNews-vectors-negative300.bin
          image: rwthacis/python-mllib
          name: mllib
          resources: {}
          volumeMounts:
            - mountPath: /app/model
              name: mllib-w2v-model
      restartPolicy: Always
      volumes:
        - name: mllib-w2v-model
          persistentVolumeClaim:
            claimName: mllib-w2v-model
status: {}
