apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - env:
            - name: LAS2PEER_ETH_HOST
              value: ethereum:8545
            - name: LAS2PEER_PORT
              value: '32077'
            - name: NODE_ID_SEED
              value: '1'
            - name: HYE_SERVICE_AGENT_NAME
              value: hyeAgent
            - name: HYE_SERVICE_AGENT_PW
              value: changeme
            - name: FRONTEND_URLS
              value: https://hye.tech4comp.dbis.rwth-aachen.de/
            - name: WEBCONNECTOR_URL
              value: https://hye.tech4comp.dbis.rwth-aachen.de/hye-youtube/
          ports:
          - containerPort: 32077
            protocol: TCP
          - containerPort: 32077
            protocol: UDP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8001
            portocol: TCP
          image: rwthacis/hye-youtube-proxy
          name: proxy
          resources: {}
          volumeMounts:
            - mountPath: /app/las2peer/node-storage
              name: node-storage
      restartPolicy: Always
      volumes:
        - name: node-storage
          persistentVolumeClaim:
            claimName: proxy-node-storage
status: {}
