apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  ports:
    - name: "32077tcp"
      port: 32077
      targetPort: 32077
      protocol: TCP
      nodePort: 32077
    - name: "32077udp"
      port: 32077
      targetPort: 32077
      nodePort: 32077
      protocol: UDP
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8001"
      port: 8001
      targetPort: 8001
  type: NodePort
  selector:
    io.kompose.service: proxy
status:
  loadBalancer: {}
